blog/urls.py
from django.urls import path
from . import views

app_name = 'blog'

urlpatterns = [
    # None
    path('', views.index, name='index'),
    path('<int:post_id>/', views.detail, name='detail'),
]

job/urls.py
from django.urls import path
from . import views

app_name = 'job'

urlpatterns = [
    # None
    path('', views.index, name='index'),
]

portfolio/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('job.urls', namespace='job')),
    path('blog/', include('blog.urls', namespace='blog')),

]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

blog/models.py
from django.db import models
from django.utils import timezone


class Post(models.Model):

    title = models.CharField(max_length=250)
    pub_date = models.DateTimeField(default=timezone.now)
    image = models. ImageField(upload_to='images/')
    body = models.TextField()

    def __str__(self):
        return self.title


class Quotes(models.Model):
    quote = models.TextField()
    author = models.CharField(max_length=20)

    class Meta:
        verbose_name_plural = "Quotes of the day"

    def __str__(self):
        return self.quote[:20]+"... -> "+self.author

job/models.py
from django.db import models


class Job(models.Model):
    image = models.ImageField(upload_to='images/')
    summary = models.CharField(max_length=250)

    def __str__(self):
        return self.summary[:15]

blog/views.py
from django.shortcuts import render, get_object_or_404, HttpResponse
from .models import Post, Quotes


def index(request):
    if request.method == 'GET' and request.GET.get('query') != None:
        query = request.GET.get('query')
        posts = Post.objects.filter(
            title__icontains=query)
        quotes = Quotes.objects.order_by('-pk')[:1]

        for quote in quotes:
            quote = get_object_or_404(Quotes, pk=quote.id)
        return render(request, 'blog/index.html', {'posts': posts, 'quote': quote})

    else:
        posts = Post.objects.order_by('-pub_date')
        quotes = Quotes.objects.order_by('-pk')[:1]
        for quote in quotes:
            quote = get_object_or_404(Quotes, pk=quote.id)
        return render(request, 'blog/index.html', {'posts': posts, 'quote': quote})


def detail(request, post_id):
    post = get_object_or_404(Post, pk=post_id)
    return render(request, 'blog/detail.html', {'post': post})

job/views.py
from django.shortcuts import render
from .models import Job


def index(request):
    jobs = Job.objects.all()
    return render(request, 'job/home.html', {'jobs': jobs})

blog/templates/blog/detail.html
{% extends 'base.html' %}

{% block blogactive %}active{% endblock blogactive %}

{% block title %}Blog-Details{% endblock title %}

{% block content %}
<!-- all posts -->
<div class="container">

    <div class="row">
        <!-- Blog Entries Column -->
        <div class="col-md-12">

            <h1 class="my-4">{{ post.title }}</h1>
            <hr>
            <p> Posted on {{ post.pub_date }}</p>
            <hr>

            <!-- Blog Post -->
            <div class="card mb-4">
                <img class="card-img-top" src="{{ post.image.url }}" alt="Card image cap" width="750px" height="450px">
                <div class="card-body">
                    <p class="card-text">{{ post.body }}</p>
                </div>
            </div>

        </div>
    </div>

</div>
<!-- /.row -->

</div>

{% endblock content %}

blog/templates/blog/index.html
{% extends 'base.html' %}

{% block blogactive %}active{% endblock blogactive %}

{% block title %}Blog{% endblock title %}

{% block content %}
<div class="container">
    <div class="pt-3 text-center">
        <h1>Deven's blog</h1>
    </div>
    <br><br><br>
</div>
<!-- all posts -->
<div class="container">

    <div class="row">
        <!-- Blog Entries Column -->
        <div class="col-md-8">

            <h1 class="my-4">Latest posts</h1>
            <hr>

            <!-- Blog Post -->

            {% for post in posts %}
            <div class="card mb-4">
                <img class="card-img-top" src="{{ post.image.url }}" alt="Card image cap" width="750px" height="300px">
                <div class="card-body">
                    <h2 class="card-title">{{ post.title }}</h2>
                    <p class="card-text">{{ post.body|truncatewords:15 }}</p>
                    <a href="{% url 'blog:detail' post.id %}" class="btn btn-primary">Read More →</a>
                </div>
                <div class="card-footer text-muted">
                    Posted on {{ post.pub_date }}
                </div>
            </div>
            {% endfor %}
        </div>

        <!-- Sidebar Widgets Column -->
        <div class="col-md-4">

            <!-- Search Widget -->
            <div class="card my-4">
                <h5 class="card-header">Search</h5>
                <div class="card-body">
                    <form action="{% url 'blog:index' %}" , method="GET">
                        {% csrf_token %}
                        <div class="input-group">
                            <input type="text" name="query" class="form-control" placeholder="Search for...">
                            <span class="input-group-btn">
                                <button class="btn btn-secondary" type="submit">Go!</button>
                            </span>
                        </div>
                    </form>
                </div>
            </div>

            <!-- Side Widget -->
            <div class="card my-4">
                <h5 class="card-header">Quotes of the day</h5>
                <div class="card-body">
                    <i class="fas fa-quote-left"></i>
                    {{ quote.quote }}
                    <i class="fas fa-quote-right"></i>
                    <div class="text-muted text-right">
                        {{ quote.author }}
                    </div>
                </div>
            </div>

        </div>

    </div>
    <!-- /.row -->
</div>
{% endblock content %}

job/templates/base.html
<!doctype html>
<html lang="en">
{% load static %}

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="Mark Otto, Jacob Thornton, and Bootstrap contributors">
    <meta name="generator" content="Jekyll v3.8.5">
    <title>{% block title %}{% endblock title %}</title>

    <!-- Bootstrap core CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/css/bootstrap.min.css" integrity="sha384-GJzZqFGwb1QTTN6wy59ffF1BuGJpLSa9DkKMp0DgiMDm4iYMj70gZWKYbI706tWS"
        crossorigin="anonymous">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.6.3/css/all.css" integrity="sha384-UHRtZLI+pbxtHCWp1t77Bi1L4ZtiqrqD80Kn4Z8NTSRyMA2Fd33n5dQ8lWUE00s/"
        crossorigin="anonymous">

    <style>
        .bd-placeholder-img {
        font-size: 1.125rem;
        text-anchor: middle;
      }

      @media (min-width: 768px) {
        .bd-placeholder-img-lg {
          font-size: 3.5rem;
        }
      }
    </style>

</head>

<body>
    <header>
        <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
            <a class="navbar-brand" style="font-size: 40px; font-style: italic;" href="{% url 'job:index' %}">Anonym De Deven</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav"
                aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div>
            <div class="collapse navbar-collapse" id="navbarNav" style="">
                <ul class="navbar-nav ml-auto">
                    <li class="nav-item">
                        <a class="nav-link" href="https://twitter.com/IDeVeN4Adh"><i class="fab fa-twitter"></i>
                            Twitter</a>
                    </li>
                     <li class="nav-item">
                        <a class="nav-link" href="https://www.facebook.com/pyratedcracker"><i class="fab fa-facebook"></i>
                            Facebook</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="https://www.facebook.com/pyratedcracker"><i class="fab fa-linkedin"></i>
                            Linkedin</a>
                    </li>
                
                   
                </ul>
            </div>
                <div style="font-size: 40px; margin-left: 330px;">
                     <ul class="navbar-nav ml-auto" style="background: #525558; border-radius: 10px;">
                    <li class="nav-item">
                        <a class="nav-link" href="#"><i
                                class="fas fa-home"></i> Home</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link {% block blogactive %}{% endblock blogactive %}" href="{% url 'blog:index' %}"><i
                                class="fas fa-blog"></i> Blog</a>
                    </li>



                    <li class="nav-item">
                        <a class="nav-link " href="#"> <i class="fas fa-phone"></i> Contact</a>
                    </li>
                     </ul>
                    
                </div>
            </div>
            </div>
        </nav>
    </header>

    <main role="main">


        {% block content %}

        {% endblock content %}

    </main>

    <footer class="text-muted">
        <div class="container text-center">
            <p>&copy; Anonym @K@ Deven {% now 'Y' %}</p>
        </div>
    </footer>
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo"
        crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.6/umd/popper.min.js" integrity="sha384-wHAiFfRlMFy6i5SRaxvfOCifBUQy1xHdJ/yoi7FRNXMRBu5WHdZYu1hA6ZOblgut"
        crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/js/bootstrap.min.js" integrity="sha384-B0UglyR+jN6CkvvICOB2joaf5I4l3gm9GU6Hc1og6Ls7i6U/mkkaduKaBhlAXv9k"
        crossorigin="anonymous"></script>
</body>

</html>

job/templates/job/home.html
{% extends 'base.html' %}
{% load staticfiles %}
{% block title %}Portfolio{% endblock title %}

{% block content %}
<section class="jumbotron text-center">
    <div class="container">
        <h1 class="jumbotron-heading">Welcome to Anonym de Deven's Blog.</h1>
        <p class="lead text-muted">Life is a beautiful lie. Enjoy every moment accepting  a better version of you. Does it seems paradoxial? But it is what it is cheers.   </p>
        <p>
            <a href="mailto:devendraa769@gmail.com" class="btn btn-primary my-2">Email me</a>
        </p>
        <!-- <img src="{% static 'deven.jpg' %}" class="img-fluid img-thumbnail" alt="image" height="400px" width="700px"> -->
    </div>
</section>

<div class="album py-5 bg-light">
    <div class="container">
        <div class="row">
            {% for job in jobs %}
            <div class="col-md-4">
                <div class="card mb-4 shadow-sm">
                    <img src="{{ job.image.url }}" alt="image" class="card-image-top" height="288px">
                    <div class="card-body">
                        <p class="card-text">{{ job.summary }}</p>
                    </div>
                </div>
            </div>
            {% endfor %}
        </div>
    </div>
</div>

{% endblock content %}